drivers: hv: dxgkrnl: Fix forward port error due to eventfd_signal change
Forward port patch build failure due to change in eventfd_signal function.
Since b7638ad0c7802ea854599ce753d0e6d20690f7e2 eventfd_signal takes only one parameter

drivers/hv/dxgkrnl/dxgmodule.c: In function 'signal_host_cpu_event':
drivers/hv/dxgkrnl/dxgmodule.c:178:17: error: too many arguments to function 'eventfd_signal'
  178 |                 eventfd_signal(event->cpu_event, 1);
      |                 ^~~~~~~~~~~~~~
In file included from drivers/hv/dxgkrnl/dxgmodule.c:15:
./include/linux/eventfd.h:87:20: note: declared here
   87 | static inline void eventfd_signal(struct eventfd_ctx *ctx)
      |

Signed-off-by: ankino17 <29777681+ankino17@users.noreply.github.com>